### ISSUE TITLE
3.1.16版本libalibabacloud-idst-speech3.so core

### ISSUE THREAD

**Issue by 949491819** [aliyun/alibabacloud-nls-cpp-sdk#16]
[New LWP 37]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/work/online/freeswitch/bin/freeswitch -base /home/work/online/freeswitch/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI_abort () at abort.c:107
107	abort.c: No such file or directory.
[Current thread is 1 (Thread 0x7f62280c2700 (LWP 52))]
(gdb) bt
#0  __GI_abort () at abort.c:107
#1  0x00007f6275bd6768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6275cf43a5 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#2  0x00007f6275bdda5a in malloc_printerr (str=str@entry=0x7f6275cf6bf8 "malloc(): unsorted double linked list corrupted") at malloc.c:5347
#3  0x00007f6275be0d74 in _int_malloc (av=av@entry=0x7f61f8000020, bytes=bytes@entry=328) at malloc.c:3744
#4  0x00007f6275be2ed1 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3428
#5  0x00007f622b02aab6 in AlibabaNls::WebSocketTcp::framePackage(AlibabaNls::WebSocketHeaderType::OpCodeType, unsigned char const*, unsigned long, unsigned char**, unsigned long*) () from /usr/lib/libalibabacloud-idst-speech3.so
#6  0x00007f622ad34589 in AlibabaNls::ConnectNode::addAudioDataBuffer(unsigned char const*, unsigned long) () from /usr/lib/libalibabacloud-idst-speech3.so
#7  0x00007f622aedcffe in AlibabaNls::NlsEventNetWork::sendAudio(AlibabaNls::INlsRequest*, unsigned char const*, unsigned long, ENCODER_TYPE) () from /usr/lib/libalibabacloud-idst-speech3.so
#8  0x00007f622a51c7d9 in request_context_ali_t::send_audio (this=<optimized out>, data=<optimized out>, length=<optimized out>) at src/ali_asr_sdk.cpp:152
#9  0x00007f622a73a82f in asr_callback (bug=0x7f61f8059f88, user_data=0x7f61f80960c8, type=<optimized out>) at /home/work1/luke/freeswitch/src/mod/asr_tts/mod_asr/mod_asr.cpp:295
#10 0x00007f6275e01afe in switch_core_session_read_frame (session=session@entry=0x7f62040062b8, frame=frame@entry=0x7f62280bf698, flags=flags@entry=0, stream_id=stream_id@entry=0) at src/switch_core_io.c:678
#11 0x00007f6275e8f473 in audio_bridge_thread (obj=obj@entry=0x7f61f80602f0, thread=0x0) at src/switch_ivr_bridge.c:800
#12 0x00007f6275e906c2 in audio_bridge_on_exchange_media (session=0x7f62040062b8) at src/switch_ivr_bridge.c:981
#13 0x00007f6275dff7a9 in switch_core_session_run (session=0x7f62040062b8) at src/switch_core_state_machine.c:650
#14 0x00007f6275df8420 in switch_core_session_thread (thread=<optimized out>, obj=0x7f62040062b8) at src/switch_core_session.c:1736
#15 0x00007f6275df3aee in switch_core_session_thread_pool_worker (thread=0x7f6204033920, obj=<optimized out>) at src/switch_core_session.c:1800
#16 0x00007f6275d37ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007f6275c57a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 5
#5  0x00007f622b02aab6 in AlibabaNls::WebSocketTcp::framePackage(AlibabaNls::WebSocketHeaderType::OpCodeType, unsigned char const*, unsigned long, unsigned char**, unsigned long*) () from /usr/lib/libalibabacloud-idst-speech3.so
(gdb) frame 6
#6  0x00007f622ad34589 in AlibabaNls::ConnectNode::addAudioDataBuffer(unsigned char const*, unsigned long) () from /usr/lib/libalibabacloud-idst-speech3.so
(gdb) frame 7
#7  0x00007f622aedcffe in AlibabaNls::NlsEventNetWork::sendAudio(AlibabaNls::INlsRequest*, unsigned char const*, unsigned long, ENCODER_TYPE) () from /usr/lib/libalibabacloud-idst-speech3.so
(gdb) frame 8
#8  0x00007f622a51c7d9 in request_context_ali_t::send_audio (this=<optimized out>, data=<optimized out>, length=<optimized out>) at src/ali_asr_sdk.cpp:152
152	src/ali_asr_sdk.cpp: No such file or directory.
(gdb) frame 1
#1  0x00007f6275bd6768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6275cf43a5 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
155	../sysdeps/posix/libc_fatal.c: No such file or directory.
(gdb) p fmt
$1 = 0x7f6275cf43a5 "%s\n"
(gdb) p *fmt
$2 = 37 '%'
(gdb) p do_abort
$3 = do_abort
(gdb) frame 4
#4  0x00007f6275be2ed1 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3428
3428	malloc.c: No such file or directory.
(gdb) frame 3
#3  0x00007f6275be0d74 in _int_malloc (av=av@entry=0x7f61f8000020, bytes=bytes@entry=328) at malloc.c:3744
3744	in malloc.c

**Comment by xsurfer163** [comment]
内存错误，请检查接口使用是否正确，请参照短链接示例
